var BalanceUpdate = {
    TOURNAMENT_REGISTRATION : 'TOURNAMENT_REGISTRATION',
    TOURNAMENT_REGISTRATION_CANCELLED : 'TOURNAMENT_REGISTRATION_CANCELLED',
    TOURNAMENT_CANCELLED : 'TOURNAMENT_CANCELLED',
    TOURNAMENT_WINNING : 'TOURNAMENT_WINNING',
    DEPOSIT : 'DEPOSIT',
    WITHDRAWAL : 'WITHDRAWAL',
    REFUND : 'REFUND'
};

exports.BalanceUpdate = BalanceUpdate;